// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBplkyVZh6vRUHVDZucanMl95nAPdIWmhA',
    appId: '1:614179992660:web:3f797d2964d1fe0d2de9c1',
    messagingSenderId: '614179992660',
    projectId: 'pawpal-de6dd',
    authDomain: 'pawpal-de6dd.firebaseapp.com',
    storageBucket: 'pawpal-de6dd.firebasestorage.app',
    measurementId: 'G-9Z87FGSQKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCffauiqxMlH56Xfeu0cx596Eu0m9FsJEY',
    appId: '1:614179992660:android:ab1426b6d853a2702de9c1',
    messagingSenderId: '614179992660',
    projectId: 'pawpal-de6dd',
    storageBucket: 'pawpal-de6dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtjAfs9zS9XQZcL32a3g4FZ6KLdL4Sjjo',
    appId: '1:614179992660:ios:464f0fb6fefc1a702de9c1',
    messagingSenderId: '614179992660',
    projectId: 'pawpal-de6dd',
    storageBucket: 'pawpal-de6dd.firebasestorage.app',
    iosBundleId: 'com.example.pawUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtjAfs9zS9XQZcL32a3g4FZ6KLdL4Sjjo',
    appId: '1:614179992660:ios:464f0fb6fefc1a702de9c1',
    messagingSenderId: '614179992660',
    projectId: 'pawpal-de6dd',
    storageBucket: 'pawpal-de6dd.firebasestorage.app',
    iosBundleId: 'com.example.pawUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBplkyVZh6vRUHVDZucanMl95nAPdIWmhA',
    appId: '1:614179992660:web:7271456918a60fc32de9c1',
    messagingSenderId: '614179992660',
    projectId: 'pawpal-de6dd',
    authDomain: 'pawpal-de6dd.firebaseapp.com',
    storageBucket: 'pawpal-de6dd.firebasestorage.app',
    measurementId: 'G-LG519D58V8',
  );
}
